version: "4.18"
networks:
  backend:
      driver: bridge
services:
  grpc:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4443:4443"
    env_file:
      - .env
